name: Reproduce deps.clj failure on Github Actions Windows

on: push

jobs:
  build:
    runs-on: 'windows-latest'
    strategy:
      fail-fast: false
      matrix:
        deps-install: [ no-opts, independent ]

    steps:
    - uses: actions/checkout@v2

    - name: "Setup Java"
      uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: java version
      run: java -version

    - name: Create dumps dir
      run: mkdir dumps

    - name: Dir dump before
      run: |
        Tree /F > dumps\before-work-dir.txt
        Tree 'C:\Users\runneradmin\scoop\shims' /F > dumps\before-shim-dir.txt
        Tree 'C:\Program Files\PowerShell\7' /F > dumps\before-powershell-dir.txt

    - name: Install scoop
      run: |
       iwr -useb get.scoop.sh | iex
       scoop bucket add scoop-clojure https://github.com/littleli/scoop-clojure
       scoop bucket add extras
       echo "::add-path::$HOME\scoop\shims"

    - name: Install deps via scoop with no opts and run
      run: |
       scoop install deps.clj@0.0.9
       java -version
       .\bin\deps.exe -Sverbose -Sdescribe
       Get-ChildItem Env: | Export-CSV dumps\env-install-no-opts.csv
       Get-Alias | Export-CSV dumps\alias-install-no-opts.csv
      if: matrix.deps-install == 'no-opts'

    - name: Install deps via scoop with --independent and run
      run: |
       scoop install deps.clj@0.0.9 --independent
       java -version
       .\bin\deps.exe -Sverbose -Sdescribe
       Get-ChildItem Env: | Export-CSV dumps\env-install-independent.csv
       Get-Alias | Export-CSV dumps\alias-install-independent.csv
      if: matrix.deps-install == 'independent'

    - name: Run deps in a separate step
      run: |
       Get-ChildItem Env: | Export-CSV dumps\env-run-${{ matrix.deps-install }}.csv
       Get-Alias | Export-CSV dumps\alias-run-${{ matrix.deps-install }}.csv
       .\bin\deps.exe -Sverbose -Sdescribe

    - name: Dir dump after
      run: |
        Tree /F > dumps\after-work-dir.txt
        Tree 'C:\Users\runneradmin\scoop\shims' /F > dumps\after-shim-dir.txt
        Tree 'C:\Program Files\PowerShell\7' /F > dumps\after-powershell-dir.txt

    - name: Upload CSVs as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dumps
        path: dumps/**
