name: Reproduce deps.clj failure on Github Actions Windows

on: push

jobs:
  build:
    runs-on: 'windows-latest'
    strategy:
      fail-fast: false
      matrix:
        deps-install: [ no-opts, independent ]

    steps:
    - uses: actions/checkout@v2

    - name: "Setup Java"
      uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Dir dump before
      run: |
        echo "Tree /F"
        Tree /F
        echo "Tree 'C:\Users\runneradmin\scoop\shims' /F"
        Tree 'C:\Users\runneradmin\scoop\shims' /F
        echo "Tree 'C:\Program Files\PowerShell\7' /F"
        Tree 'C:\Program Files\PowerShell\7' /F

    - name: Create dumps dir
      run: mkdir dumps

    - name: Install scoop and deps.clj no opts
      run: |
       iwr -useb get.scoop.sh | iex
       scoop bucket add scoop-clojure https://github.com/littleli/scoop-clojure
       scoop bucket add extras
       scoop install deps.clj@0.0.9
       Get-ChildItem Env: | Export-CSV dumps\env-install-no-opts.csv
       Get-Alias | Export-CSV dumps\alias-install-no-opts.csv
       echo "::add-path::$HOME\scoop\shims"
      if: matrix.deps-install == 'no-opts'

    - name: Install scoop and deps.clj independent
      run: |
       iwr -useb get.scoop.sh | iex
       scoop bucket add scoop-clojure https://github.com/littleli/scoop-clojure
       scoop bucket add extras
       scoop install deps.clj@0.0.9 --independent
       Get-ChildItem Env: | Export-CSV dumps\env-install-independent.csv
       Get-Alias | Export-CSV dumps\alias-install-independent.csv
       echo "::add-path::$HOME\scoop\shims"
      if: matrix.deps-install == 'independent'

    - name: Run deps in a separate step
      run: |
       Get-ChildItem Env: | Export-CSV dumps\env-run-${{ matrix.deps-install }}.csv
       Get-Alias | Export-CSV dumps\alias-run-${{ matrix.deps-install }}.csv
       deps -Sverbose -Sdescribe

    - name: Dir dump after
      run: |
        echo "Tree /F"
        Tree /F
        echo "Tree 'C:\Users\runneradmin\scoop\shims' /F"
        Tree 'C:\Users\runneradmin\scoop\shims' /F
        echo "Tree 'C:\Program Files\PowerShell\7' /F"
        Tree 'C:\Program Files\PowerShell\7' /F

    - name: Upload CSVs as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dumps
        path: dumps/**
