name: Reproduce deps.clj failure on Github Actions Windows

on: push

jobs:
  build:
    runs-on: 'windows-latest'
    strategy:
      fail-fast: false
      matrix:
        deps-install: [ no-opts, independent ]

    steps:
    - uses: actions/checkout@v2

    - name: "Setup Java"
      uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Install scoop and deps.clj no opts
      run: |
       iwr -useb get.scoop.sh | iex
       scoop bucket add scoop-clojure https://github.com/littleli/scoop-clojure
       scoop bucket add extras
       scoop install deps.clj@0.0.9
       echo "-- start dump env --"
       Get-ChildItem Env:
       echo "-- edn dump env --"
       echo "-- start dump aliases --"
       Get-Alias
       echo "-- end dump aliases --"
       echo "::add-path::$HOME\scoop\shims"
      if: matrix.deps-install == 'no-opts'

    - name: Install scoop and deps.clj independent
      run: |
       iwr -useb get.scoop.sh | iex
       scoop bucket add scoop-clojure https://github.com/littleli/scoop-clojure
       scoop bucket add extras
       scoop install deps.clj@0.0.9 --independent
       echo "-- start dump env --"
       Get-ChildItem Env:
       echo "-- edn dump env --"
       echo "-- start dump aliases --"
       Get-Alias
       echo "-- end dump aliases --"
       echo "::add-path::$HOME\scoop\shims"
      if: matrix.deps-install == 'independent'

    - name: Run deps in a separate step
      run: |
       echo "-- start dump env --"
       Get-ChildItem Env:
       echo "-- edn dump env --"
       echo "-- start dump aliases --"
       Get-Alias
       echo "-- end dump aliases --"
       deps -Sverbose -Sdescribe
