name: Reproduce deps.clj failure on Github Actions Windows

on: push

jobs:
  build:
    runs-on: 'windows-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Install deps.exe
      run: |
        PowerShell -Command "iwr -useb https://raw.githubusercontent.com/borkdude/deps.clj/master/install.ps1 | iex"
        cd $HOME\deps.clj
        .\deps -Sdescribe
        echo "::add-path::$HOME\deps.clj"

    - name: Setup alias clojure->deps.clj
      run: |
        mkdir $HOME/bin
        New-Item -Path "$HOME\bin\clojure.exe" -ItemType SymbolicLink -Value "$HOME\deps.clj\shims\deps.exe"
        New-Item -Path "$HOME\bin\clojure.shim" -ItemType SymbolicLink -Value "$HOME\deps.clj\shims\deps.shim"
        echo "::add-path::$HOME\bin"

    - name: Tools versions
      run: |
        echo "node --version"
        node --version
        echo "java -version"
        java -version
        echo "clojure -Sdescribe"
        clojure -Sdescribe
