name: Reproduce deps.clj failure on Github Actions Windows

on: push

jobs:
  build:
    runs-on: 'windows-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Install deps.exe
      run: |
        PowerShell -Command "iwr -useb https://raw.githubusercontent.com/borkdude/deps.clj/master/install.ps1 | iex"
        echo "::add-path::$HOME\deps.clj"

    - name: Run deps.exe
      run: deps -Sdescribe
